### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nemati-ceo** [brody192/volume-filebrowser#2]
Hello, I need to use this. but I am not sure If I understand it. any video that shows how to use it. thanks

**Comment by brody192** [comment]
Please see the [readme](https://github.com/brody192/volume-filebrowser/blob/main/README.md)
and for any additional questions, you can contact me by opening a thread in the [railway discord](https://discord.gg/railway) servers #Help channel

**Comment by nemati-ceo** [comment]
I'm new to the world of railways. If it's feasible, record a video to demonstrate its functionality. This would be highly beneficial, as it can provide assistance to anyone. If you're unable to find the time, that's perfectly alright. Thank you for considering this.

**Comment by brody192** [comment]
I'm sorry but I do not have the software/inclination to produce a tutorial video, but you are free to ask me all the questions you want in our discords #Help channel
